services:
  - type: web
    name: zenkoo-bot-api
    env: docker
    dockerContext: ./bot-service
    dockerfilePath: ./bot-service/Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: APPS_SCRIPT_MEMORY_URL
        value: "https://script.google.com/macros/s/AKfycbzz-lF2u6zXrHL6ueXCdNV_fLX4IVgdVVY9szOnbafW0dyD8ghUKzUL1Lth7lP2p4DC6A/exec"
      - key: APPS_SCRIPT_MEMORY_ENABLED
        value: "false"
      - key: GOOGLE_SHEETS_MEMORY_ENABLED
        value: "false"

